name: nullidea
description: Idea Sharing Platform


version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  google_fonts: ^0.3.9
  flutter:
    sdk: flutter
  material_design_icons_flutter: 3.4.4995
  rxdart: ^0.18.0
  http: ^0.12.0+4
  flutter_spinkit: "^4.1.2"
  pin_code_fields: ^2.4.0
  countdown_flutter: ^0.1.2
  cupertino_icons: ^0.1.2
  quiver: ^2.1.3
  firebase_messaging: ^6.0.16
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/fonts/

  fonts:
  - family: Pacifico     
    fonts:
    - asset: assets/fonts/Pacifico-Regular.ttf

  - family: Ubuntu     
    fonts:
    - asset: assets/fonts/Ubuntu-Regular.ttf

