name: nullidea
description: Idea Sharing Platform


version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  image_picker: ^0.6.7+4
  image_cropper: ^1.2.3
  shared_preferences: ^0.5.8
  path_provider: ^1.6.11
  cached_network_image: ^2.2.0+1
  dio: ^3.0.9
  google_fonts: ^0.3.9
  flutter:
    sdk: flutter
  material_design_icons_flutter: 3.4.4995
  rxdart: ^0.23.0

  http: ^0.12.0+4
  flutter_spinkit: "^4.1.2"
  pin_code_fields: ^2.4.0
  countdown_flutter: ^0.1.2
  cupertino_icons: ^0.1.2
  quiver: ^2.1.3
  rflutter_alert: ^1.0.3
  curved_navigation_bar: ^0.3.3
  firebase_messaging: ^6.0.16
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/fonts/
  fonts:
    - family: postidea
      fonts:
        - asset: assets/fonts/postidea.ttf
    - family: reward
      fonts:
        - asset: assets/fonts/reward.ttf
    - family: ticket
      fonts:
        - asset: assets/fonts/ticket.ttf